sudo: false
language: go

go: 
  - 1.4.2

install:
  - go get -t -v ./...
  - go install github.com/onsi/ginkgo/ginkgo

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go tool vet -composites=false $(ls -d */ )
  - ginkgo -p -r -race -failOnPending -randomizeAllSpecs
